vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO brainboxdotcc/DPP
    REF 25006668103d0e77252b45b3098ff457a8422189 #v10.0.23
    SHA512 f15e21d62f226d1bd2cd769e2a83f735c925c27a13eaa3347714d38228f3015a82938fbed7a66101ed5d74f806c5244e212665500ecdd45be6d0a78bf76545a6
    HEAD_REF master
    PATCHES
        mq-fix-static-build.patch
)

if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
    set(BUILD_SHARED_LIBS OFF)
else()
    set(BUILD_SHARED_LIBS ON)
endif()

if("opus" IN_LIST VCPKG_FEATURE_FLAGS)
    set(BUILD_VOICE_SUPPORT ON)
else()
    set(BUILD_VOICE_SUPPORT OFF)
endif()

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    DISABLE_PARALLEL_CONFIGURE
    OPTIONS
        "-DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}"
        "-DBUILD_VOICE_SUPPORT=${BUILD_VOICE_SUPPORT}"
        "-DDPP_BUILD_TEST=OFF"
)

vcpkg_cmake_install()

vcpkg_cmake_config_fixup(NO_PREFIX_CORRECTION)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share/dpp")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")

if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
endif()

file(
    INSTALL "${SOURCE_PATH}/LICENSE"
    DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}"
    RENAME copyright
)

file(COPY "${CMAKE_CURRENT_LIST_DIR}/usage" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")

