# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: MIT
#
variables:
  osx-pool: 'PrOsx-2022-02-04'

jobs:
- template: osx/azure-pipelines.yml
  parameters:
    poolName: $(osx-pool)
